[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.18" }
bevy_egui = "0.39"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
noise = "0.9"
mlua = { version = "0.11.6", features = ["lua54", "vendored"] }
bevy-inspector-egui = "0.36"

rumpel_coords = { path = "crates/rumpel_coords" }
rumpel_blocks = { path = "crates/rumpel_blocks" }
rumpel_world = { path = "crates/rumpel_world" }
rumpel_render = { path = "crates/rumpel_render" }
rumpel_player = { path = "crates/rumpel_player" }
rumpel_modding = { path = "crates/rumpel_modding" }
rumpel_tests = { path = "crates/rumpel_tests" }
rumpel_debug = { path = "crates/rumpel_debug" }
rumpel_prelude = { path = "crates/rumpel_prelude" }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
